### ISSUE TITLE
dbbc3 multicast

### ISSUE THREAD

**Issue by gofrito** [mpifr-vlbi/dbbc3#2]
Hi Helge, 
have you tried the multicast feature from the dbbc3? Do you monitor it with a set of Python scripts? At the moment, I am  testing that out with one of the dbbc3's in Hobart.
Cheers,

**Comment by HelgeRottmann** [comment]
No, not yet, Sven has developed a rudimentary monitoring client based on multicast. This is however high on the to-do list.

**Comment by gofrito** [comment]
Good to know! We are doing some tests with it as well. I am happy to contribute some pieces when it's implemented.

**Comment by HelgeRottmann** [comment]
Added DBBC3Multicast.py parser
