### ISSUE TITLE
utilities not working due DBBC3Config() changes

### ISSUE THREAD

**Issue by jwagnerhki** [mpifr-vlbi/dbbc3#3]
Hi! Utilities and the library seem to be out of sync. 

For example running setupDBBC3_OCT_D.py leads to

__init__() takes exactly 2 arguments (1 given)

Probably 
  config = DBBC3Config()
should now be something like
  config = DBBC3Config({ 'mode':'OCT_D', 'majorVersion':str(args.ver) })

I tried the above and a few minor additions to get subsequent errors out of the way (d7e81c5, aed026c; under cluster 'oper' account so these got unexpectedly tagged as your commits) but ran into additional issues. There would be too much to edit at the moment, and you might already have local but not yet pushed changes.

Perhaps you could git-tag the latest still operational version?

**Comment by HelgeRottmann** [comment]
Fixed code to work with DBBC3Config changes
